services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      # Sincroniza os arquivos locais com o container para desenvolvimento
      - ./:/var/www
    networks:
      - laravel_network
    # Permite que o container acesse o localhost da máquina hospedeira (seu Postgres externo)
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    # Mapeia a configuração do Nginx que criaremos abaixo
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge